security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                target: home  # Aquí defino que al cerrar sesión me redirija automáticamente al inicio

    access_control:
        # === ACCESO POR ROLES DEFINIDO ===

        # 1. Solo usuarios con rol administrador pueden acceder a /admin/*
        - { path: ^/admin, roles: ROLE_ADMIN }

        # 2. Solo usuarios propietarios pueden acceder a /proprietaire/*
        - { path: ^/proprietaire, roles: ROLE_PROPRIETAIRE }

        # 3. Solo usuarios clientes pueden acceder a /client/*
        - { path: ^/client, roles: ROLE_CLIENT }

        # 4. Acceso libre a login y registro
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }

        # 5. si no esta registrado 
        # Permitir acceso público a la página de inicio
        - { path: ^/$, roles: PUBLIC_ACCESS }

# Todo lo demás requiere estar autenticado
       #- { path: ^/, roles: IS_AUTHENTICATED_FULLY }


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

