services:
  php:
    build: .
    container_name: agencia_php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db


  db:  # <--- Este es el nombre correcto
    image: mysql:8.0
    container_name: agencia_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inmobiliaria
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: agencia_phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db_data:
